#!/usr/bin/env node

var sys = require('util'),
	path = require('path'),
	argv = require('optimist').argv;

var help = [
	"usage: buck [options]",
	"",
	"starts Buck",
	"",
	"options:",
	"  -p             Port that you want the home server to run on      [80]",
	"  -l             File to log to      [/var/log/buck.log]",
	"  -h, --help     You're staring at it",
].join('\n');

if (argv.h || argv.help) {
	return sys.puts(help);
}

var esIndex = 'buck';
var options = {
	port: argv.p || 80,
	logFile: argv.l || '/var/log/buck.log'
};

// @todo: this is not cool
global.logFile = options.logFile;

var buck = require('./server/main');

buck.start(options,function(err,server){
	var logger = require('./server/logger');

	process.on('uncaughtException', function(err) {
		logger.w.info(' ');
		logger.w.info(' ');
		logger.w.info(' ');
		logger.w.info('-============================================================-');
		logger.w.info('Caught exception: ' + err);
		logger.w.info('Memory usage: ' + sys.inspect(process.memoryUsage()));
		logger.w.info('Uptime: ' + process.uptime() + 's');
		logger.w.info('-============================================================-');
		logger.w.info(' ');
		logger.w.info(' ');
		logger.w.info(' ');
	});

	if (err){
		return logger.w.info('Error starting Buck '+ err.message);
	}

	logger.w.info('Buck ready to leak @ http://127.0.0.1:'+options.port);
});